# Generated by Django 4.2.1 on 2023-06-13 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edit_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('edit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_comment', to='wiki.edit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_comment_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
