# Generated by Django 4.2.1 on 2023-06-13 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_edit_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Original_Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original', to='wiki.article')),
            ],
        ),
    ]
