# Generated by Django 4.2.1 on 2023-07-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_remove_user_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='edit',
            name='group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
