# Generated by Django 4.2.1 on 2023-06-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_remove_article_status_edit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='timestamp',
            new_name='create_timestamp',
        ),
        migrations.AddField(
            model_name='article',
            name='edit_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
