# Generated by Django 4.2.1 on 2023-07-19 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_edit_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edit',
            name='score',
        ),
    ]
