# Generated by Django 4.2.1 on 2023-05-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='item_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='listings',
            name='item_photo',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='listings',
            name='starting_price',
            field=models.FloatField(default=0),
        ),
    ]
