# Generated by Django 4.2.1 on 2023-05-20 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bid_comment_remove_comments_comment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='listing_user',
        ),
    ]
