# Generated by Django 4.2.1 on 2023-05-21 08:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_listing_listing_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bid',
            name='current_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='starting_price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
