# Generated by Django 4.2.1 on 2023-05-21 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bid_bid_amount_alter_bid_current_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bid_amount',
        ),
    ]
