# Generated by Django 4.2.1 on 2023-07-15 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_group_remove_user_group_expert_delete_article_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='expert',
        ),
    ]
